import{setupLanguage,t,lang,localize}from'./i18n.js';
const labels={
ar:{back:'العودة للتشكيلات',augments:'الأوجمنتس المرتبطة',tips:'ملاحظات اللعب',stages:'خطة المراحل',stage:'المرحلة',board:'وحدات البورد',items:'الأيتمز الأساسية',priority:'أولوية الأيتمز',early:'بداية اللعبة',flex:'الوحدات المرنة',position:'التمركز',alt:'بدائل وبناءات أخرى',note:'ملاحظات مهمة'},
en:{back:'Back to comps',augments:'Related Augments',tips:'Play Notes',stages:'Stage Plan',stage:'Stage',board:'Board Units',items:'Core Items',priority:'Item Priority',early:'Early Game',flex:'Flex Units',position:'Positioning',alt:'Alternatives & Alt Builds',note:'Important Notes'},
ja:{back:'構成一覧に戻る',augments:'関連オーグメント',tips:'プレイのポイント',stages:'ステージ別プラン',stage:'ステージ',board:'盤面ユニット',items:'主要アイテム',priority:'アイテム優先度',early:'序盤',flex:'フレックスユニット',position:'配置',alt:'代替案・別ビルド',note:'重要なポイント'}};
const slug=new URLSearchParams(location.search).get('slug');let all=[];
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function render(){const c=all.find(x=>x.slug===slug);const root=document.querySelector('#situational-detail');const L=labels[lang]||labels.ar;document.querySelector('[data-sit-label="back"]').textContent=L.back;document.querySelector('.sit-back').href=lang==='ar'?'comps.html':lang+'/comps.html';if(!c){root.innerHTML='<p class="empty">'+t('notFound')+'</p>';return}const g=c.guide||{};const localized=(key)=>lang==='ar'?(g.ar?.[key]||g[key]):lang==='ja'?(g.ja?.[key]||g[key]):(g.en?.[key]||g[key]);const panel=(title,body)=>body?'<section class="sit-panel"><h2>'+title+'</h2>'+body+'</section>':'';document.title=localize(c.title)+' — MokaTroy TFT';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
const board=(g.board||[]).map(u=>'<span>'+esc(u)+'</span>').join('');const items=(g.items||[]).map(x=>'<div class="sit-item-row"><strong>'+esc(x.unit)+'</strong><div>'+x.items.map(i=>'<span>'+esc(i)+'</span>').join('')+'</div></div>').join('');const aug=(c.augments||[]).map(a=>'<span>'+esc(a)+'</span>').join('');const stages=(c.stages||[]).map(s=>'<div class="sit-stage"><strong>'+L.stage+' '+s.stage+'</strong><div class="sit-muted">'+esc(localize(s.text))+'</div></div>').join('');
root.innerHTML='<section class="sit-hero"><span class="situational-label">SITUATIONAL · SET 18</span><h1>'+esc(localize(c.title))+'</h1><p class="sit-muted">'+esc(localize(c.style))+'</p><p class="sit-muted">'+esc(localize(c.note))+'</p></section><div class="sit-grid">'+panel(L.board,'<div class="sit-augments">'+board+'</div>')+panel(L.items,items)+panel(L.priority,'<div class="sit-augments">'+(g.priority||[]).map((i,n)=>'<span><b>'+(n+1)+'.</b> '+esc(i)+'</span>').join('')+'</div>')+panel(L.early,'<div class="sit-muted">'+(g.early||[]).map(esc).join(' · ')+'</div>')+panel(L.flex,'<div class="sit-muted">'+(g.flex||[]).map(x=>'<p>'+esc(x)+'</p>').join('')+'</div>')+panel(L.position,'<p class="sit-muted">'+esc(localized('position'))+'</p>')+panel(L.alt,'<p class="sit-muted">'+esc(localized('alt'))+'</p>')+panel(L.augments,'<div class="sit-augments">'+aug+'</div>')+panel(L.tips,'<p class="sit-muted">'+esc(localize(c.note))+'</p>')+'</div>'+panel(L.stages,'<div class="sit-stages">'+stages+'</div>');
}
fetch('data/situational-comps.json').then(r=>r.json()).then(x=>{all=x;render()}).catch(()=>{document.querySelector('#situational-detail').innerHTML='<p class="empty">Unable to load guide.</p>'});setupLanguage(render);
