import{setupLanguage,t,lang,localize}from'./i18n.js';
const labels={ar:{back:'العودة للتشكيلات',augments:'الأوجمنتس المرتبطة',tips:'ملاحظات اللعب',stages:'خطة المراحل',stage:'المرحلة',board:'البورد',items:'الأيتمز الأساسية',priority:'أولوية الأيتمز',early:'بداية اللعبة',flex:'الوحدات المرنة',position:'التمركز',alt:'بدائل وبناءات أخرى'},en:{back:'Back to comps',augments:'Related Augments',tips:'Play Notes',stages:'Stage Plan',stage:'Stage',board:'Board',items:'Core Items',priority:'Item Priority',early:'Early Game',flex:'Flex Units',position:'Positioning',alt:'Alternatives & Alt Builds'},ja:{back:'構成一覧に戻る',augments:'関連オーグメント',tips:'プレイのポイント',stages:'ステージ別プラン',stage:'ステージ',board:'盤面',items:'主要アイテム',priority:'アイテム優先度',early:'序盤',flex:'フレックスユニット',position:'配置',alt:'代替案・別ビルド'}};
const slug=new URLSearchParams(location.search).get('slug');let all=[];
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const key=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const itemAliases={'krakensfury':'krakenslayer','faeemblem':'spatula','ravageremblem':'spatula','florafatalisemblem':'spatula'};
const boardPositions={
'unrivaled-khazix':['p4','p3','p6','p8','p1','p2','p7','p5'],
'ravager-elise':['p4','p3','p6','p8','p1','p2','p7','p5'],
'veigar-consuming-flora':['p4','p3','p6','p8','p1','p2','p7','p5'],
'fae-tristana':['p4','p3','p6','p8','p1','p2']};
function champSrc(name){return'assets/champions/'+key(name)+'.png'}
function itemSrc(name){return'assets/items/'+(itemAliases[key(name)]||key(name))+'.png'}
function img(src,alt,cls=''){return'<img class="'+cls+'" src="'+src+'" alt="'+esc(alt)+'" loading="lazy" onerror="this.style.display=\'none\'">'}
function render(){const c=all.find(x=>x.slug===slug),root=document.querySelector('#situational-detail'),L=labels[lang]||labels.ar;if(!root)return;const back=document.querySelector('[data-sit-label="back"]');if(back)back.textContent=L.back;const backLink=document.querySelector('.sit-back');if(backLink)backLink.href=lang==='ar'?'comps.html':lang+'/comps.html';if(!c){root.innerHTML='<p class="empty">'+t('notFound')+'</p>';return}
const g=c.guide||{},localized=k=>lang==='ar'?(g.ar?.[k]||g[k]):lang==='ja'?(g.ja?.[k]||g[k]):(g.en?.[k]||g[k]),txt=v=>typeof v==='object'?(v[lang]||v.en||v.ar||''):v,panel=(title,body,cls='')=>body?'<section class="sit-panel '+cls+'"><h2>'+title+'</h2>'+body+'</section>':'';
document.title=txt(c.title)+' — MokaTroy TFT';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
const slots=boardPositions[c.slug]||[];const carryItems=new Map((g.items||[]).map(x=>[key(x.unit),x.items||[]]));
const board=(g.board||[]).map((u,i)=>{const pos=slots[i]||'p9',its=carryItems.get(key(u))||[];return'<div class="board-slot '+pos+'"><article class="unit-hex hex-small" data-unit="'+esc(u)+'"><img src="'+champSrc(u)+'" alt="'+esc(u)+'"><span class="unit-cost"></span><span class="unit-name">'+esc(u)+'</span>'+(its.length?'<span class="unit-items">'+its.slice(0,3).map(it=>'<span class="unit-item" title="'+esc(it)+'">'+img(itemSrc(it),it)+'</span>').join('')+'</span>':'')+'</article></div>'}).join('');
const itemRows=(g.items||[]).map(x=>'<div class="sit-item-row"><div class="sit-carry">'+img(champSrc(x.unit),x.unit,'sit-unit-icon')+'<strong>'+esc(x.unit)+'</strong></div><div class="sit-item-icons">'+x.items.map(i=>'<span class="sit-item" title="'+esc(i)+'">'+img(itemSrc(i),i,'sit-item-icon')+'<small>'+esc(i)+'</small></span>').join('')+'</div></div>').join('');
const priority=(g.priority||[]).map((i,n)=>'<span><b>'+(n+1)+'.</b> '+img(itemSrc(i),i,'priority-item-icon')+esc(i)+'</span>').join('');const aug=(c.augments||[]).map(a=>'<span>'+esc(a)+'</span>').join('');const stages=(c.stages||[]).map(s=>'<div class="sit-stage"><strong>'+L.stage+' '+s.stage+'</strong><div class="sit-muted">'+esc(txt(s.text))+'</div></div>').join('');
root.innerHTML='<section class="sit-hero"><span class="situational-label">SITUATIONAL · SET 18</span><h1>'+esc(txt(c.title))+'</h1><p class="sit-muted">'+esc(txt(c.style))+'</p><p class="sit-muted">'+esc(txt(c.note))+'</p></section>'+panel(L.board,'<div class="tft-board">'+board+'</div>')+'<div class="sit-grid">'+panel(L.items,itemRows)+panel(L.priority,'<div class="sit-augments">'+priority+'</div>')+panel(L.early,'<div class="sit-muted">'+(g.early||[]).map(esc).join(' · ')+'</div>')+panel(L.flex,'<div class="sit-muted">'+(g.flex||[]).map(x=>'<p>'+esc(txt(x))+'</p>').join('')+'</div>')+panel(L.position,'<p class="sit-muted">'+esc(localized('position'))+'</p>')+panel(L.alt,'<p class="sit-muted">'+esc(localized('alt'))+'</p>')+panel(L.augments,'<div class="sit-augments">'+aug+'</div>')+panel(L.tips,'<p class="sit-muted">'+esc(txt(c.note))+'</p>')+'</div>'+panel(L.stages,'<div class="sit-stages">'+stages+'</div>');
}
fetch('data/situational-comps.json').then(r=>r.json()).then(x=>{all=x;render()}).catch(()=>{const r=document.querySelector('#situational-detail');if(r)r.innerHTML='<p class="empty">Unable to load guide.</p>'});setupLanguage(render);
