const isTraits=location.pathname.endsWith('traits.html');
const tiers=['S','A','B','C'];
const data=isTraits?[
 {name:'Riftbeast',tier:'A',img:'assets/traits/riftbeast.png'}, {name:'Blackthorn',tier:'A',img:'assets/traits/blackthorn.png'}, {name:'Blossom',tier:'A',img:'assets/traits/blossom.png'}, {name:'Juggernaut',tier:'A',img:'assets/traits/juggernaut.png'}, {name:'Hunter',tier:'B',img:'assets/traits/hunter.png'}, {name:'Invoker',tier:'B',img:'assets/traits/invoker.png'}, {name:'Vanguard',tier:'B',img:'assets/traits/vanguard.png'}, {name:'Inferno',tier:'B',img:'assets/traits/inferno.png'}
]:[
 {name:'Infinity Edge',tier:'A',img:'assets/items/infinityedge.png'}, {name:"Guinsoo's Rageblade",tier:'A',img:'assets/items/guinsoosrageblade.png'}, {name:'Spear of Shojin',tier:'A',img:'assets/items/spearofshojin.png'}, {name:'Hand of Justice',tier:'A',img:'assets/items/handofjustice.png'}, {name:'Titan’s Resolve',tier:'A',img:'assets/items/titansresolve.png'}, {name:'Bloodthirster',tier:'B',img:'assets/items/bloodthirster.png'}, {name:'Blue Buff',tier:'B',img:'assets/items/bluebuff.png'}, {name:'Bramble Vest',tier:'B',img:'assets/items/bramblevest.png'}, {name:'Gargoyle Stoneplate',tier:'B',img:'assets/items/gargoylestoneplate.png'}, {name:'Sunfire Cape',tier:'B',img:'assets/items/sunfirecape.png'}
];
const labels={S:'S TIER',A:'A TIER',B:'B TIER',C:'C TIER'};
function render(){const q=document.querySelector('#tier-search').value.trim().toLowerCase();document.querySelector('#tier-board').innerHTML=tiers.map(t=>{const entries=data.filter(x=>x.tier===t&&x.name.toLowerCase().includes(q));return entries.length?'<section class="tier-row tier-'+t.toLowerCase()+'"><div class="tier-label">'+labels[t]+'</div><div class="tier-items">'+entries.map(x=>'<article class="tier-entry"><img src="'+x.img+'" alt="" onerror="this.style.display=\'none\'"><span>'+x.name+'</span></article>').join('')+'</div></section>':''}).join('')||'<p class="empty">مفيش نتائج مطابقة.</p>'}
document.querySelector('#tier-search').addEventListener('input',render);document.querySelectorAll('.lang-toggle').forEach(b=>b.addEventListener('click',()=>{document.documentElement.lang='en';document.documentElement.dir='ltr';document.querySelectorAll('nav a').forEach(a=>{const m={'الرئيسية':'Home','التشكيلات':'Comps','الأيتمز':'Items','التريتس':'Traits','الباتش':'Patch'};a.textContent=m[a.textContent]||a.textContent});document.querySelector('#tier-search').placeholder='Search…';b.textContent='عربي'}));render();