import {localize,t} from './i18n.js';
import {initAbilityTooltips} from './tooltip.js';
initAbilityTooltips();
export function compCard(c){return `<a class="comp-card" style="--accent:${c.color}" href="comp.html?slug=${encodeURIComponent(c.slug)}"><div class="card-top"><span class="tier ${c.tier.toLowerCase()}">${c.tier} TIER</span><span>${localize(c.style)}</span></div><h3>${localize(c.name)}</h3><p>${localize(c.summary)}</p><div class="unit-list">${c.units.slice(0,4).map(u=>`<span class="unit-chip" data-unit="${u.name.en}" data-unit-ar="${u.name.ar}">${localize(u.name)}</span>`).join('')}</div></a>`}
function hex(u,size=''){const photo=u.image?`<img src="${u.image}" alt="${localize(u.name)}">`:`<span class="unit-fallback">${localize(u.name).slice(0,1)}</span>`;return `<article class="unit-hex cost-${u.cost||1}${size==='mini'?' hex-mini':size?' hex-small':''}" data-unit="${u.name.en}" data-unit-ar="${u.name.ar}">${photo}<span class="unit-cost">${u.cost||''}</span><span class="unit-name">${localize(u.name)}</span></article>`}
function boardUnit(u,place){return u?`<div class="board-slot ${place}">${hex(u,'small')}</div>`:''}
export function detail(c,patch){const traits=c.traits.map(x=>`<span class="trait-pill">${localize(x.name)} <b>${x.count}</b></span>`).join('');const itemPriority=c.items.map(x=>`<span class="priority-pill">${localize(x)}</span>`).join('');const augments=(c.augments||[]).map(localize).map(x=>`<span class="augment-pill">${x}</span>`).join('');const stageCards=(c.stages||[]).map(s=>`<article class="stage-card"><span>${t('stage')} ${s.stage}</span><p>${localize(s.text)}</p></article>`).join('');const early=(c.earlyUnits||[]).map(u=>hex(u,'mini')).join('');const flex=(c.flex||[]).map(f=>`<p>${f.units.join(' · ')} <span>${f.label}</span></p>`).join('');const board=c.units.length>=5?`<section class="board-panel"><h2>${t('positioning')}</h2><div class="tft-board">${boardUnit(c.units[4],'p1')}${boardUnit(c.units[5],'p2')}${boardUnit(c.units[1],'p3')}${boardUnit(c.units[0],'p4')}${boardUnit(c.units[7],'p5')}${boardUnit(c.units[2],'p6')}${boardUnit(c.units[6],'p7')}${boardUnit(c.units[3],'p8')}${boardUnit(c.units[8],'p9')}</div></section>`:'';return `<a class="back-link" href="comps.html">${t('back')}</a><div class="comp-layout"><aside class="comp-sidebar"><div class="tier-emblem ${c.tier.toLowerCase()}">${c.tier}</div><h1>${localize(c.name)}</h1><p class="playstyle">${localize(c.style)}</p><div class="side-divider"></div>${traits?`<h3>${t('traits')}</h3><div class="trait-stack">${traits}</div>`:''}${augments?`<h3>${t('augmentPriority')}</h3><div class="augment-stack">${augments}</div>`:''}<p class="side-note">${t('patch')} ${patch?.version||''} · Set 18</p></aside><main class="comp-dashboard"><section class="unit-strip"><div class="strip-title"><p class="eyebrow">${localize(c.name)}</p><h2>${t('units')}</h2></div><div class="strip-units">${c.units.map(u=>hex(u,'small')).join('')}</div></section><section class="info-row cols-${1+(early?1:0)+(flex?1:0)}">${early?`<article class="info-panel"><h2>${t('earlyUnits')}</h2><div class="early-list">${early}</div><small class="early-note">${t('earlyNote')}</small></article>`:''}<article class="info-panel"><h2>${t('itemPriority')}</h2><div class="priority-list">${itemPriority}</div></article>${flex?`<article class="info-panel"><h2>${t('flexUnits')}</h2>${flex}</article>`:''}</section>${board}<section class="tips-panel"><h2>${t('howToPlay')}</h2><p>${localize(c.guide)}</p>${(c.sections||[]).map(s=>`<div class="guide-section"><h3>${localize(s.title)}</h3>${(s.body||[]).map(p=>`<p>${localize(p)}</p>`).join('')}${s.bullets&&s.bullets.length?`<ul class="guide-list">${s.bullets.map(b=>`<li>${localize(b)}</li>`).join('')}</ul>`:''}</div>`).join('')}</section><section class="stage-guide"><h2>${t('stageGuide')}</h2><div class="stage-grid">${stageCards}</div></section></main></div>`}

function changeRow(ch){const badgeKey=ch.type==='adjust'?'adjustments':ch.type+'s';return `<li class="change-row change-${ch.type}"><span class="change-badge">${t(badgeKey)}</span><div><b>${localize(ch.name)}</b><p>${localize(ch.detail)}</p></div></li>`}
function changeGroup(cat,label,items){if(!items.length) return '';return `<section class="patch-group"><h3>${label} <span class="patch-count">${items.length}</span></h3><ul class="change-list">${items.map(changeRow).join('')}</ul></section>`}
export function patchPage(p){
  if(!p) return '';
  const cats=[['champion','categoryChampion'],['trait','categoryTrait'],['item','categoryItem'],['augment','categoryAugment'],['system','categorySystem']];
  const main=(p.changes||[]).filter(c=>c.category!=='hotfix');
  const hotfix=(p.changes||[]).filter(c=>c.category==='hotfix');
  const order={buff:0,adjust:1,nerf:2};
  const groups=cats.map(([cat,key])=>changeGroup(cat,t(key),main.filter(c=>c.category===cat).sort((a,b)=>order[a.type]-order[b.type]))).join('');
  const hotfixGroup=hotfix.length?`<section class="patch-group hotfix-group"><h3>${t('categoryHotfix')}</h3><p class="hotfix-note">${t('hotfixNote')}</p><ul class="change-list">${hotfix.sort((a,b)=>order[a.type]-order[b.type]).map(changeRow).join('')}</ul></section>`:'';
  return `<p class="eyebrow">${t('patchPageEyebrow')} ${p.version}</p><h1 class="page-title">${t('patchPageTitle')}</h1><p class="page-subtitle">${localize(p.highlights||p.summary)}</p>${p.releaseDate?`<p class="patch-release">${t('released')} ${p.releaseDate}</p>`:''}<div class="patch-groups">${groups}${hotfixGroup}</div>`;
}
